[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
wynd = "*"
lume = "*"
dotenv = "0.15.0"
paste = "1.0.15"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }